BigNoid/Aeon-Nox

- 1080i/SkinSettings.xml
- 1080i/View_501_LowList.xml
- 1080i/View_50_List.xml
- 1080i/View_55_TriPanel.xml
- 1080i/variables.xml
- language/English (US)/strings.po
- language/English/strings.po
- language/German/strings.po
I just had the pleasure of testing this marvelous skin for the first time the other day. While having my movie snob friends over, however, it became abundantly clear I needed an option to disable the display of movie ratings altogether. Helps keeping an open mind. 
Anyway, this PR introduces the possibility to toggle ratings globally for views of type List, LowList and TriPanel. Ratings are displayed regardless of the setting, if the list is sorted by them.
> Add option to hide video ratings in List, LowList and TriPanel

- 1080i/script-NextAired-TVGuide.xml
- 1080i/script-NextAired-TVGuide2.xml
- 21x9/script-NextAired-TVGuide.xml
- 21x9/script-NextAired-TVGuide2.xml
This fixes the label2 dates in the Next Aired window. I finally properly cloned the repo rather just submitting patches through the browser, hope this shows up correctly.
> Fix hidden date in Next Aired

- 1080i/MusicOSD.xml
This fixes the playlist button in the music OSD so that the music viz closes to display the playlist. Assumed the textoffset is not needed, please disregard if it is.
> Fix playlist button in music OSD

- 1080i/DialogAddonInfo.xml
- 1080i/Includes_LiveTV.xml
- 1080i/MyVideoNav.xml
- 1080i/MyWeather.xml
- 1080i/View_501_LowList.xml
- 1080i/View_51_InfoWall.xml
- 1080i/includes.xml
- 21x9/DialogAddonInfo.xml
- 21x9/MyWeather.xml
- 21x9/includes.xml
[DialogAddonInfo] Remove Rollback button + Add Auto-update radiobutton
[LowList] Fix double artist genre
[InfoWall] Music include scrollbar alignment fix
[Includes_LiveTV] Add XML declaration
Add missing ButtonCommonValues includes
Add randomize true tag for extrafanart fadelabel
Remove and add buttons to DialogAddonInfo [here](http://forum.kodi.tv/showthread.php?tid=231270&pid=2136968#pid2136968) and [here](http://forum.kodi.tv/showthread.php?tid=231270&pid=2161413#pid2161413)
I noticed double artist genre in Lowlist, it may be a Jarvis issue since both the regular ListItem.Genre and ListItem.Property(Artist_Genre) are displayed it appears twice when using latest Jarvis nightlies.
InfoWall scrollbar for the music section was not left enough, off about 50 pixels.
Added some missing …
> Some fixes and Jarvis additions

- 1080i/script-NextAired-TVGuide2.xml
onright for the Next Aired TV Guide 2 settings button (8) was set to an ID not  in the xml so it doesn't put focus on the guide causing the need to exit and re-enter. A slight annoyance when I accidentally open the side menu when navigating too quickly :smiley:
> Fix sidemenu onright of TVGuide2.xml

- 1080i/Includes_LiveTV_Views.xml
The EPG background texture for the standard timeline view was missing. Re-added it. Fixed double rendering of channel logo and outline for IDs 11, 12, 13.
> EPG Item Background Missing on Standard Timeline View

- 1080i/variables.xml
Add parenthesis surrounding NowRecordingChannel using prefix/postfix, missing closing bracket after color formatting for pvr infoline and add double spacing before/after pipe symbol for system infoline . Other stuff is just whitespace auto deleted when saving.
PVR.HasNonRecordingTimer is the only InfoLine that has "-" in it so I kept it white like the pipe symbol.
> Missing bracket

- 1080i/MyPVRRecordings.xml
Content path wasn't listing subdirectories so changed from Path to FolderPath and it seems to work for all items now.
I also noticed some alignment issues.
I can squash if you prefer :smiley:
> [MyPVRRecordings] Fix subdirectory listing

- 1080i/Settings.xml
- 1080i/View_503_Wall.xml
- 21x9/View_503_Wall.xml
- language/English/strings.po
@BigNoid Not sure if we need to change it to a different one but the localized On string is not appearing, like for the InfoPanel as an example.
> LibrarySettings > MediaSettings + Wall view only show InfoPanel when focused

- 1080i/MyPlaylist.xml
- 21x9/MyPlaylist.xml
@BigNoid This has been bugging me for awhile, since Gotham I think. It is the longest running bug that I couldn't see the solution for. So happy I found the cause but disappointed that it took me so long... I thought it was just a weird bug for the playlist window that never got fixed in each Kodi update :smiley:
Edit: Forgot 21:9 again, I just added it now :wink:
> Fix playlist sidemenu slide animation on first open

- 1080i/DialogAddonSettings.xml
There seems to be a few add-ons that use 200 as a standard button id and it breaks the functionality of that button so I changed the image id to 2000 instead.
For example if you use openweathermap extended and click location 1 it will prevent DialogKeyboard from opening.
> Change image id (breaks any button with id of 200)

- 1080i/DialogFullScreenInfo.xml
info on LiveTV:
"up" switches between "FullPlot" and small "PlotOutline"
"left/right" switches between "actual" and "Next"-Plot-info
> add "What's next" on LiveTV Fullscreeninfo

- addon.xml
Looks much nicer with the 9th screenshot referenced ;)
> fix missing screenshot reference

- 1080i/Includes.xml
This adds some visible-tags to PVR-sideblade menu, e.g.
"Channels" is only visible, if you are not in MyPVRChannels,
"Recordings" is only visible, i you are not in MyPVRRecordings,
and so on ...
"Channel goups" is only visible in MyPVRChannels and MyPVRGuide. It is IMHO
not needed in other PVR windows.
BTW: can you please backport this and the previous PR to krypton ;)
Thx
> better visibility for PVR entries in sb-menu

- 1080i/variables.xml
When PlotOutline is empty then no Plot is shown for movies so I changed the VAR to fallback to plot when outline IsEmpty
> VAR fix for empty PlotOutline in Wall InfoPanel

- 1080i/Includes_LiveTV.xml
- 1080i/Includes_LiveTV_Views.xml
- 1080i/MyPVRChannels.xml
Address https://github.com/BigNoid/Aeon-Nox/issues/680 by displaying Sub Channels by using "ChannelNumberLabel" instead of "ChannelNumber" - with additional changes to accommodate spacing
Simply changing the label:-
And Reszing:-
> Subchannels

- 1080i/View_501_LowList.xml
- 1080i/custom_1129_Views.xml
Activate Low List support for Music Videos, and choose suitable fields for the right hand side.
Low List
and Low List low toggle
and Dialogue Information
> Add LowList support for Music Videos

- 1080i/DialogFullScreenInfo.xml
Extends point 1. in https://github.com/BigNoid/Aeon-Nox/issues/616 to show more information when playing music videos and concerts.
Changes Music Video playback information from the uninformative:-
To one which has similar information you'd get on Episodes or Films.
The Plot/Cast buttons are hidden as Cast appears to always be un-populated.  Studio logo behaviour is now cloning that  when viewing "information" on episodes (e.g. display text when no image) - e.g. Epic Amsterdam here.
Also works well with DVD sized artwork.
> Show information for music videos when full screen info shown.

- 1080i/SkinSettings.xml
- 1080i/custom_1121_HomeMenuCustomizer.xml
- 1080i/custom_1122_BackgroundCustomizer.xml
- 1080i/custom_1123_OnClickCustomizer.xml
@BigNoid 
[10035 was changed to Skin Settings](https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L4828).
[Using 13007 instead](https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L5927).
> Update string used for Reset label

- 1080i/DialogSettings.xml
- 1080i/VideoOSD.xml
@BigNoid I couldn't find a better button for the new subtitles settings dialog so I changed the onclick to open that instead. The new dialog has a Download subtitles button so I added a condition to the fade animation that already hides DialogSettings when SliderDialog is visible.
> Add OSDSubtitleSettings button
